# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' getneighborhood_fast
#' @description
#' an efficient function to find the neighborhood based on the matrix of position and a pre-defined cutoff
#'
#' @param x is a n-by-2 matrix of position.
#' @param cutoff is a threashold of Euclidean distance to decide whether a spot is an neighborhood of another spot. For example, if the Euclidean distance between spot A and B is less than cutoff, then A is taken as the neighbourhood of B. 
#' @return A sparse matrix containing the neighbourhood
#'
#' @export
getneighborhood_fast <- function(x, cutoff) {
    .Call(`_SpatialAnno_getneighborhood_fast`, x, cutoff)
}

update_W_l <- function(x_l, y_l, Ez_l, Ci_l) {
    .Call(`_SpatialAnno_update_W_l`, x_l, y_l, Ez_l, Ci_l)
}

update_W_u <- function(x_u, R_u, Ez_u, C_ui, N_u) {
    .Call(`_SpatialAnno_update_W_u`, x_u, R_u, Ez_u, C_ui, N_u)
}

#' 
#'  
#' 
#' 
#' 
#' 
#' 
update_W0 <- function(X, R, Ez, Ci, N) {
    .Call(`_SpatialAnno_update_W0`, X, R, Ez, Ci, N)
}

init_Sgm <- function(y_l, Ez_l, Ci_l, Mu_l, diagSigma) {
    .Call(`_SpatialAnno_init_Sgm`, y_l, Ez_l, Ci_l, Mu_l, diagSigma)
}

update_Sgm_u <- function(R_u, Ez_u, C_ui, Mu_u, N_u, diagSigma) {
    .Call(`_SpatialAnno_update_Sgm_u`, R_u, Ez_u, C_ui, Mu_u, N_u, diagSigma)
}

update_Lam_l <- function(x_l, W_l, Ez_l, C_li, homo) {
    .Call(`_SpatialAnno_update_Lam_l`, x_l, W_l, Ez_l, C_li, homo)
}

update_Lam_u <- function(R_u, X_u, W_u, Ez_u, C_ui, homo) {
    .Call(`_SpatialAnno_update_Lam_u`, R_u, X_u, W_u, Ez_u, C_ui, homo)
}

update_Lam <- function(R, X, W, Ez, Ci, homo) {
    .Call(`_SpatialAnno_update_Lam`, R, X, W, Ez, Ci, homo)
}

getPairDist <- function(x) {
    .Call(`_SpatialAnno_getPairDist`, x)
}

calYenergy2D_sp <- function(y, Adj, K, alpha, beta) {
    .Call(`_SpatialAnno_calYenergy2D_sp`, y, Adj, K, alpha, beta)
}

obj_beta <- function(y, R, Adj, K, alpha, beta) {
    .Call(`_SpatialAnno_obj_beta`, y, R, Adj, K, alpha, beta)
}

update_sigma <- function(X_m, rho, R, alpha, bet) {
    .Call(`_SpatialAnno_update_sigma`, X_m, rho, R, alpha, bet)
}

update_Rsigma <- function(X_m, rho, R, alpha, bet, eta) {
    .Call(`_SpatialAnno_update_Rsigma`, X_m, rho, R, alpha, bet, eta)
}

update_alpha <- function(X_m, rho, R, bet) {
    .Call(`_SpatialAnno_update_alpha`, X_m, rho, R, bet)
}

update_Ralpha <- function(X_m, rho, R, bet, eta) {
    .Call(`_SpatialAnno_update_Ralpha`, X_m, rho, R, bet, eta)
}

update_beta_j <- function(X_m, rho, R, alpha, N, j, lfc) {
    .Call(`_SpatialAnno_update_beta_j`, X_m, rho, R, alpha, N, j, lfc)
}

update_Rbeta_j <- function(X_m, rho, R, alpha, eta, j, lfc) {
    .Call(`_SpatialAnno_update_Rbeta_j`, X_m, rho, R, alpha, eta, j, lfc)
}

Mstep_marker <- function(X_m, rho, R, alpha, bet, sigma, N, lfc) {
    invisible(.Call(`_SpatialAnno_Mstep_marker`, X_m, rho, R, alpha, bet, sigma, N, lfc))
}

update_etajk <- function(X_m, alpha, bet, j, k) {
    .Call(`_SpatialAnno_update_etajk`, X_m, alpha, bet, j, k)
}

add_mu <- function(rho, alpha, bet, eta) {
    .Call(`_SpatialAnno_add_mu`, rho, alpha, bet, eta)
}

Mstep_Rmarker <- function(X_m, rho, lfc, R, alpha, bet, eta, mu, sigma) {
    invisible(.Call(`_SpatialAnno_Mstep_Rmarker`, X_m, rho, lfc, R, alpha, bet, eta, mu, sigma))
}

log_cp_marker <- function(X_m, mu_k_m, sigma) {
    .Call(`_SpatialAnno_log_cp_marker`, X_m, mu_k_m, sigma)
}

log_cp_Rmarker <- function(X_m, mu_k_m, sigma) {
    .Call(`_SpatialAnno_log_cp_Rmarker`, X_m, mu_k_m, sigma)
}

em_marker <- function(X_m, rho, lfc, maxIter, eps, verbose) {
    .Call(`_SpatialAnno_em_marker`, X_m, rho, lfc, maxIter, eps, verbose)
}

em_Rmarker <- function(X_m, rho, lfc, maxIter, eps, verbose) {
    .Call(`_SpatialAnno_em_Rmarker`, X_m, rho, lfc, maxIter, eps, verbose)
}

em <- function(X_m, X_u, rho, lfc, R_int, Pi_int, alpha_int, bet_int, sigma_int, Mu_u_int, W_u_int, Sgm_u_int, Lam_u_int, maxIter, eps, verbose, homo = FALSE, diagSigmak = FALSE) {
    .Call(`_SpatialAnno_em`, X_m, X_u, rho, lfc, R_int, Pi_int, alpha_int, bet_int, sigma_int, Mu_u_int, W_u_int, Sgm_u_int, Lam_u_int, maxIter, eps, verbose, homo, diagSigmak)
}

emR <- function(X_m, X_u, rho, lfc, R_int, Pi_int, alpha_int, bet_int, sigma_int, Mu_u_int, W_u_int, Sgm_u_int, Lam_u_int, maxIter, eps, verbose, homo = FALSE, diagSigmak = FALSE) {
    .Call(`_SpatialAnno_emR`, X_m, X_u, rho, lfc, R_int, Pi_int, alpha_int, bet_int, sigma_int, Mu_u_int, W_u_int, Sgm_u_int, Lam_u_int, maxIter, eps, verbose, homo, diagSigmak)
}

runICM_sp <- function(X_m, X_u, y, Adj, Pi, mu, sigma, logdSigma, W_u, Lam_u, Mu_u, Sgm_u, Sgm_ui, C_u, C_ui, beta_grid, beta, maxIter_ICM) {
    .Call(`_SpatialAnno_runICM_sp`, X_m, X_u, y, Adj, Pi, mu, sigma, logdSigma, W_u, Lam_u, Mu_u, Sgm_u, Sgm_ui, C_u, C_ui, beta_grid, beta, maxIter_ICM)
}

icmem <- function(X_m, X_u, Adj, rho, lfc, y_int, Pi, xi_int, xi_grid, alpha_int, bet_int, sigma_int, Mu_u_int, W_u_int, Sgm_u_int, Lam_u_int, maxIter, maxIter_ICM, eps, verbose, homo = FALSE, diagSigmak = FALSE) {
    .Call(`_SpatialAnno_icmem`, X_m, X_u, Adj, rho, lfc, y_int, Pi, xi_int, xi_grid, alpha_int, bet_int, sigma_int, Mu_u_int, W_u_int, Sgm_u_int, Lam_u_int, maxIter, maxIter_ICM, eps, verbose, homo, diagSigmak)
}

runICM_sp_anno <- function(X_m, X_u, y, Adj, Pi, mu, sigma, logdSigma, W_u, Lam_u, Mu_u, Sgm_u, Sgm_ui, C_u, C_ui, beta_grid, beta, maxIter_ICM) {
    .Call(`_SpatialAnno_runICM_sp_anno`, X_m, X_u, y, Adj, Pi, mu, sigma, logdSigma, W_u, Lam_u, Mu_u, Sgm_u, Sgm_ui, C_u, C_ui, beta_grid, beta, maxIter_ICM)
}

icmem_anno <- function(X_m, X_u, Adj, rho, lfc, y_int, Pi, xi_int, xi_grid, alpha_int, bet_int, sigma_int, Mu_u_int, W_u_int, Sgm_u_int, Lam_u_int, maxIter, maxIter_ICM, eps, verbose, homo = FALSE, diagSigmak = FALSE) {
    .Call(`_SpatialAnno_icmem_anno`, X_m, X_u, Adj, rho, lfc, y_int, Pi, xi_int, xi_grid, alpha_int, bet_int, sigma_int, Mu_u_int, W_u_int, Sgm_u_int, Lam_u_int, maxIter, maxIter_ICM, eps, verbose, homo, diagSigmak)
}

runICM_sp_factor <- function(X_m, X_u, y, Adj, Pi, mu, sigma, logdSigma, W_u, Lam_u, Mu_u, Sgm_u, Sgm_ui, C_u, C_ui, beta_grid, beta, maxIter_ICM) {
    .Call(`_SpatialAnno_runICM_sp_factor`, X_m, X_u, y, Adj, Pi, mu, sigma, logdSigma, W_u, Lam_u, Mu_u, Sgm_u, Sgm_ui, C_u, C_ui, beta_grid, beta, maxIter_ICM)
}

icmem_factor <- function(X_m, X_u, Adj, rho, lfc, y_int, Pi, xi_int, xi_grid, alpha_int, bet_int, sigma_int, Mu_u_int, W_u_int, Sgm_u_int, Lam_u_int, maxIter, maxIter_ICM, eps, verbose, homo = FALSE, diagSigmak = FALSE) {
    .Call(`_SpatialAnno_icmem_factor`, X_m, X_u, Adj, rho, lfc, y_int, Pi, xi_int, xi_grid, alpha_int, bet_int, sigma_int, Mu_u_int, W_u_int, Sgm_u_int, Lam_u_int, maxIter, maxIter_ICM, eps, verbose, homo, diagSigmak)
}

runICM_sp_spatialfactor <- function(X_m, X_u, y, Adj, Pi, mu, sigma, logdSigma, W_u, Lam_u, Mu_u, Sgm_u, Sgm_ui, C_u, C_ui, beta_grid, beta, maxIter_ICM) {
    .Call(`_SpatialAnno_runICM_sp_spatialfactor`, X_m, X_u, y, Adj, Pi, mu, sigma, logdSigma, W_u, Lam_u, Mu_u, Sgm_u, Sgm_ui, C_u, C_ui, beta_grid, beta, maxIter_ICM)
}

icmem_spatialfactor <- function(X_m, X_u, Adj, rho, lfc, y_int, Pi, xi_int, xi_grid, alpha_int, bet_int, sigma_int, Mu_u_int, W_u_int, Sgm_u_int, Lam_u_int, maxIter, maxIter_ICM, eps, verbose, homo = FALSE, diagSigmak = FALSE) {
    .Call(`_SpatialAnno_icmem_spatialfactor`, X_m, X_u, Adj, rho, lfc, y_int, Pi, xi_int, xi_grid, alpha_int, bet_int, sigma_int, Mu_u_int, W_u_int, Sgm_u_int, Lam_u_int, maxIter, maxIter_ICM, eps, verbose, homo, diagSigmak)
}

runICM_sp_spatialanno <- function(X_m, X_u, y, Adj, Pi, mu, sigma, logdSigma, W_u, Lam_u, Mu_u, Sgm_u, Sgm_ui, C_u, C_ui, beta_grid, beta, maxIter_ICM) {
    .Call(`_SpatialAnno_runICM_sp_spatialanno`, X_m, X_u, y, Adj, Pi, mu, sigma, logdSigma, W_u, Lam_u, Mu_u, Sgm_u, Sgm_ui, C_u, C_ui, beta_grid, beta, maxIter_ICM)
}

icmem_spatialanno <- function(X_m, X_u, Adj, rho, lfc, y_int, Pi, xi_int, xi_grid, alpha_int, bet_int, sigma_int, Mu_u_int, W_u_int, Sgm_u_int, Lam_u_int, maxIter, maxIter_ICM, eps, verbose, homo = FALSE, diagSigmak = FALSE) {
    .Call(`_SpatialAnno_icmem_spatialanno`, X_m, X_u, Adj, rho, lfc, y_int, Pi, xi_int, xi_grid, alpha_int, bet_int, sigma_int, Mu_u_int, W_u_int, Sgm_u_int, Lam_u_int, maxIter, maxIter_ICM, eps, verbose, homo, diagSigmak)
}

runICM_sp_annofactor <- function(X_m, X_u, y, Adj, Pi, mu, sigma, logdSigma, W_u, Lam_u, Mu_u, Sgm_u, Sgm_ui, C_u, C_ui, beta_grid, beta, maxIter_ICM) {
    .Call(`_SpatialAnno_runICM_sp_annofactor`, X_m, X_u, y, Adj, Pi, mu, sigma, logdSigma, W_u, Lam_u, Mu_u, Sgm_u, Sgm_ui, C_u, C_ui, beta_grid, beta, maxIter_ICM)
}

icmem_annofactor <- function(X_m, X_u, Adj, rho, lfc, y_int, Pi, xi_int, xi_grid, alpha_int, bet_int, sigma_int, Mu_u_int, W_u_int, Sgm_u_int, Lam_u_int, maxIter, maxIter_ICM, eps, verbose, homo = FALSE, diagSigmak = FALSE) {
    .Call(`_SpatialAnno_icmem_annofactor`, X_m, X_u, Adj, rho, lfc, y_int, Pi, xi_int, xi_grid, alpha_int, bet_int, sigma_int, Mu_u_int, W_u_int, Sgm_u_int, Lam_u_int, maxIter, maxIter_ICM, eps, verbose, homo, diagSigmak)
}

runICM_Rsp <- function(X_m, X_u, y, Adj, Pi, mu, sigma, logdSigma, W_u, Lam_u, Mu_u, Sgm_u, Sgm_ui, C_u, C_ui, beta_grid, beta, maxIter_ICM) {
    .Call(`_SpatialAnno_runICM_Rsp`, X_m, X_u, y, Adj, Pi, mu, sigma, logdSigma, W_u, Lam_u, Mu_u, Sgm_u, Sgm_ui, C_u, C_ui, beta_grid, beta, maxIter_ICM)
}

icmemR <- function(X_m, X_u, Adj, rho, lfc, y_int, Pi, xi_int, xi_grid, alpha_int, bet_int, sigma_int, Mu_u_int, W_u_int, Sgm_u_int, Lam_u_int, maxIter, maxIter_ICM, eps, verbose, homo = FALSE, diagSigmak = FALSE) {
    .Call(`_SpatialAnno_icmemR`, X_m, X_u, Adj, rho, lfc, y_int, Pi, xi_int, xi_grid, alpha_int, bet_int, sigma_int, Mu_u_int, W_u_int, Sgm_u_int, Lam_u_int, maxIter, maxIter_ICM, eps, verbose, homo, diagSigmak)
}

#' @noRd
#' 
calculateWeight <- function(X, nPCs) {
    .Call(`_SpatialAnno_calculateWeight`, X, nPCs)
}

wpcaCpp <- function(X, nPCs, weighted = TRUE) {
    .Call(`_SpatialAnno_wpcaCpp`, X, nPCs, weighted)
}

